using System;
using System.IO;
using System.Text;
using System.Windows;
using Microsoft.Web.WebView2.Core;

namespace YoutubeDownloaderWpf.Views
{
    public partial class LoginWindow : Window
    {
        public string SavedCookiePath { get; private set; }
        public string SavedUserAgent { get; private set; } // Biến mới để lưu UserAgent

        public LoginWindow()
        {
            InitializeComponent();
            InitializeAsync();
        }

        async void InitializeAsync()
        {
            await webView.EnsureCoreWebView2Async(null);
            // Xóa cookie cũ để đảm bảo sạch sẽ
            webView.CoreWebView2.CookieManager.DeleteAllCookies();
            webView.Source = new Uri("https://www.youtube.com");
        }

        private async void SaveCookies_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                var cookieManager = webView.CoreWebView2.CookieManager;
                var cookies = await cookieManager.GetCookiesAsync("https://www.youtube.com");

                if (cookies.Count == 0)
                {
                    MessageBox.Show("Chưa thấy cookies. Hãy đăng nhập và F5 lại trang Youtube!", "Thông báo");
                    return;
                }

                // 1. LẤY COOKIES CHUẨN NETSCAPE
                StringBuilder sb = new StringBuilder();
                sb.AppendLine("# Netscape HTTP Cookie File");
                sb.AppendLine("# This file was generated by YoutubeDownloaderWpf");

                foreach (var cookie in cookies)
                {
                    // Domain: Phải bắt đầu bằng dấu chấm nếu là tên miền (vd .youtube.com)
                    string domain = cookie.Domain;
                    if (!domain.StartsWith(".") && !System.Text.RegularExpressions.Regex.IsMatch(domain, @"^\d"))
                        domain = "." + domain;

                    // Include Subdomains? (TRUE nếu có dấu chấm đầu)
                    string flag = domain.StartsWith(".") ? "TRUE" : "FALSE";

                    string path = string.IsNullOrEmpty(cookie.Path) ? "/" : cookie.Path;
                    string secure = cookie.IsSecure ? "TRUE" : "FALSE";

                    // Xử lý Expiration: Chuyển về Unix Timestamp (giây)
                    long expires = 253402300799; // Mặc định năm 2999

                    try
                    {
                        // Kiểm tra kiểu dữ liệu của Expires (WebView2 đôi khi trả về double hoặc DateTime)
                        dynamic rawExpires = cookie.Expires;

                        if (rawExpires is DateTime dt)
                        {
                            if (dt != DateTime.MinValue)
                                expires = new DateTimeOffset(dt).ToUnixTimeSeconds();
                        }
                        else if (rawExpires is double d)
                        {
                            // Nếu số > 0 thì lấy, nếu = 0 (session) thì giữ nguyên max
                            if (d > 0) expires = (long)d;
                        }
                    }
                    catch { }

                    // Ghi dòng cookie: domain  flag  path  secure  expires  name  value
                    sb.AppendLine($"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{cookie.Name}\t{cookie.Value}");
                }

                string cookiePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "cookies.txt");
                File.WriteAllText(cookiePath, sb.ToString());
                SavedCookiePath = cookiePath;

                // 2. LẤY USER-AGENT (QUAN TRỌNG ĐỂ TRÁNH BỊ CHẶN)
                // Lấy chuỗi UserAgent thực tế của WebView2
                string userAgent = await webView.CoreWebView2.ExecuteScriptAsync("navigator.userAgent");
                // Kết quả trả về có dấu ngoặc kép "...", cần xóa đi
                if (!string.IsNullOrEmpty(userAgent))
                {
                    userAgent = userAgent.Trim('"');
                    string uaPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "user-agent.txt");
                    File.WriteAllText(uaPath, userAgent);
                    SavedUserAgent = userAgent;
                }

                MessageBox.Show("Đã lưu Cookies và User-Agent thành công!\nHãy thử tải lại video hội viên.", "Thành công");
                this.DialogResult = true;
                this.Close();
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Lỗi: {ex.Message}");
            }
        }
    }
}